### PR TITLE
Release: laddr v2.3.11

### PR DESCRIPTION
**Pull request by themightychris**
- README updates
- Add project roles/applications feature (thanks @kevin-dexter !)
- Remove person details summary from blog post byline
- Add slack and saml2 integrations as standard
- Add UI for managing event segments

### CODE REVIEW

**Comment by themightychris** [comment]
## TODO
- [ ] Test roles/applications feature and review syntax

**Comment by AndrewNatoli** [comment]
The event dates and times in the event editor now show properly when editing an existing event ❤️ 

Segments are wonderful. Segment locations appropriately show / don't show on the main agenda list based on whether or not they were set. 👍 

What's the roles / applications feature?

**Comment by AndrewNatoli** [comment]
@themightychris Using the "Clone from git" method, are there any special steps to initialize the projects / tags / etc. tables? I'm missing those out of the box and I can't create projects or anything to manually create them which works in the version I have in production.

**Comment by themightychris** [comment]
@AndrewNatoli all tables get created automatically when they are first written to. If you see any SELECT queries causing errors because any table does not exist that's a bug in the query code not handling a table not existing as an empty result. 

The roles/applications feature would let projects post "We need a UX designer" and then someone apply to be assigned that role. It's intended to replace the system where people just add themselves to projects, so that projects can declare their needs and moderate adding people. It needs some testing/polish before release that isn't tough but I just haven't gotten to

**Comment by AndrewNatoli** [comment]
@themightychris I'll reset my local instance and try again but the projects page wasn't "failing" gracefully for me on this branch as it originally did in my install for Open Charlotte. Will update you soon hopefully

**Comment by AndrewNatoli** [comment]
🙌 
@themightychris would it be helpful for anyone to test anything new yet or are you still in the middle of a master plan?

**Comment by themightychris** [comment]
@AndrewNatoli perfect timing, I *just* got the full local dev workflow working, could you give it a try?

With recent versions of [Habitat](http://habitat.sh) and [Docker](https://www.docker.com/) installed on your (preferably Mac or Linux) machine:

```bash
git checkout develop
export HAB_DOCKER_OPTS="-p 7080:7080"
hab studio enter
start-all-local
sup-log
# watch supervisor log until mysql stops initializing, then hit CTRL+C
watch-site
```

At that point you should be able to see an instance at http://localhost:7080 and any edits should be reflected live

(There's some template compilation issue affecting the homepage currently but the rest of the site works, I need to figure out running the right version of the template engine)

**Comment by themightychris** [comment]
That template compilation issue is fixed now, run `git holo source fetch --all` if you've already initialized

**Comment by themightychris** [comment]
I just added a second holobranch for codeforphilly's overlay, so if you run this instead you'll see Code for Philly's version of laddr!

```bash
EMERGENCE_HOLOBRANCH=codeforphilly watch-site
```

**Comment by themightychris** [comment]
I've demoted this release from 2.4.0 to 2.3.11 and am moving all the nontrivial unfinished work to feature branches for later release

**Pull request merged**
